# Generated by Django 5.2.8 on 2025-11-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pics/default_pic.jpeg",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
    ]
