# Generated by Django 5.2.8 on 2025-12-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='school_class',
            field=models.CharField(default='pi1', help_text='Example: 10A, 4, 8A', max_length=20),
            preserve_default=False,
        ),
    ]
