# Generated by Django 5.2.8 on 2025-11-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_picture",
            field=models.ImageField(blank=True, null=True, upload_to="book_covers/"),
        ),
    ]
