# Generated by Django 5.2.8 on 2025-11-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_book_cover_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_picture",
            field=models.ImageField(
                blank=True, default="default_cover.png", null=True, upload_to=""
            ),
        ),
    ]
