# Generated by Django 5.2.8 on 2025-12-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bookreview_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='why_read',
            field=models.TextField(default='nice book', help_text='Why did you read this book?', max_length=500),
            preserve_default=False,
        ),
    ]
